/* generated by ice9 */
/* runtime */
#include <errno.h>
#include <stdlib.h>
#include <stdio.h>
typedef int T_int;
typedef char * T_string;
int __read(){
char _readbuf[512]; int i;
if (!fgets(_readbuf, 512, stdin)) { puts("READ ERROR"); exit(-1);}
errno = 0;
 i = strtol(_readbuf, NULL, 10);if (errno) perror("CONVERSION ERROR");
return i;
}
#define _WRITEI(i)	printf("%d\n", i)
#define _WRITESI(i)	printf("%d", i)
#define _WRITES(s)	printf("%s\n", s)
#define _WRITESS(s)	printf("%s", s)

/* global declarations */
int n, t;
int a[100];

/* main program */
main()
{
_WRITES("Input length of array (1-100):");
n = __read();
if (((n < 1) || (n > 100))) {
_WRITES("wrong");
exit(0);
}
n = (n - 1);
{ int i;
for (i = 0; i <= n; ++i) {
_WRITESS("Input ");
_WRITESI((i + 1));
_WRITESS(": ");
a[i] = __read();
}
}
{ int i;
for (i = 0; i <= (n - 1); ++i) {
{ int j;
for (j = (i + 1); j <= n; ++j) {
if ((a[i] > a[j])) {
t = a[i];
a[i] = a[j];
a[j] = t;
}
}
}
}
}
_WRITES("Sorted list:");
{ int i;
for (i = 0; i <= n; ++i) {
_WRITEI(a[i]);
}
}
}
